### ISSUE TITLE
How to use with blueprints

### ISSUE THREAD

**Issue by tonycpsu** [jmcarp/flask-apispec#16]
I want to do put my REST API calls in a Flask blueprint and document them using the APISpec extension, like so:

```python
from flask import Flask, Blueprint
from flask_apispec import use_kwargs, marshal_with

from apispec import APISpec
from flask_apispec.extension import FlaskApiSpec

from marshmallow import fields, Schema

app = Flask(__name__)
blueprint = Blueprint("api", "api")

class PetSchema(Schema):
    class Meta:
        fields = ('name', 'category', 'size')

@blueprint.route('/pets')
@use_kwargs({'category': fields.Str(), 'size': fields.Str()})
@marshal_with(PetSchema(many=True))
def get_pets(**kwargs):
    return [{"name": "Scooby", "category": "dog", "size": "large"}]

spec = APISpec(
    title='pets',
    version='v1',
    plugins=['apispec.ext.marshmallow'],
)
docs = FlaskApiSpec(app)

docs.register(get_pets)
app.run()
```

But this yields the following:
```
Traceback (most recent call last):
  File "./foo.py", line 29, in <module>
    docs.register(get_pets)
  File "/usr/local/lib/python2.7/site-packages/flask_apispec/extension.py", line 72, in register
    paths = self.view_converter.convert(target, endpoint, blueprint)
  File "/usr/local/lib/python2.7/site-packages/flask_apispec/apidoc.py", line 24, in convert
    rules = self.app.url_map._rules_by_endpoint[endpoint]
KeyError: 'get_pets'
```

I see that the `register` method has a `blueprint` parameter, but passing `blueprint=blueprint` doesn't work, nor does `blueprint="api"`.

I'd like to know if it's possible to make this work with the project as-is, and if not, would like to see this feature implemented and documented as an example.

**Comment by shaicantor** [comment]
Hey @tonycpsu, 
It works.
You just forgot to register your blueprint.

```python
app.register_blueprint(blueprint)
```

And then, just like you tried write:
```python
docs.register(get_pets, blueprint="api")
```

**Comment by tonycpsu** [comment]
Yep, that did it.  Thanks!
