### ISSUE TITLE
TypeError: fields2parameters() missing 1 required keyword-only argument: 'default_in'

### ISSUE THREAD

**Issue by d42** [jmcarp/flask-apispec#165]
```
➜ python petstore.py 
Traceback (most recent call last):
  File "petstore.py", line 73, in <module>
    docs.register(get_pet)
  File "/tmp/apispectest/env/lib/python3.7/site-packages/flask_apispec/extension.py", line 121, in register
    resource_class_args, resource_class_kwargs)
  File "/tmp/apispectest/env/lib/python3.7/site-packages/flask_apispec/extension.py", line 68, in _defer
    bound()
  File "/tmp/apispectest/env/lib/python3.7/site-packages/flask_apispec/extension.py", line 136, in _register
    paths = self.view_converter.convert(target, endpoint, blueprint)
  File "/tmp/apispectest/env/lib/python3.7/site-packages/flask_apispec/apidoc.py", line 42, in convert
    return [self.get_path(rule, target, **kwargs) for rule in rules]
  File "/tmp/apispectest/env/lib/python3.7/site-packages/flask_apispec/apidoc.py", line 42, in <listcomp>
    return [self.get_path(rule, target, **kwargs) for rule in rules]
  File "/tmp/apispectest/env/lib/python3.7/site-packages/flask_apispec/apidoc.py", line 53, in get_path
    for method, view in six.iteritems(operations)
  File "/tmp/apispectest/env/lib/python3.7/site-packages/flask_apispec/apidoc.py", line 54, in <dictcomp>
    if method.lower() in (set(valid_methods) - {'head'})
  File "/tmp/apispectest/env/lib/python3.7/site-packages/flask_apispec/apidoc.py", line 66, in get_operation
    'parameters': self.get_parameters(rule, view, docs, parent),
  File "/tmp/apispectest/env/lib/python3.7/site-packages/flask_apispec/apidoc.py", line 97, in get_parameters
    extra_params += converter(schema, **options) if args else []
TypeError: fields2parameters() missing 1 required keyword-only argument: 'default_in'
```
```
pip freeze
apispec==3.0.0
Click==7.0
Flask==1.1.1
flask-apispec==0.8.3
itsdangerous==1.1.0
Jinja2==2.10.1
MarkupSafe==1.1.1
marshmallow==3.2.0
six==1.12.0
webargs==5.5.1
Werkzeug==0.16.0
```
halp

**Comment by ivancarrancho** [comment]
![1__docker-compose_exec_backend_bash__docker_](https://user-images.githubusercontent.com/13756563/65646961-8afd0d00-dfc2-11e9-8800-344377eaa3db.png)

![1__docker-compose_exec_backend_bash__docker_](https://user-images.githubusercontent.com/13756563/65647019-ca2b5e00-dfc2-11e9-8ec1-c078c950ac04.png)


same issue

**Comment by nicobytes** [comment]
Hello!

I use the latests version show this:

```
INFO:werkzeug:172.31.0.1 - - [25/Sep/2019 23:36:04] "POST /api/graphql/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/app/app/main.py", line 8, in <module>
    from .core import app_setup  # noqa
  File "/app/app/core/app_setup.py", line 12, in <module>
    from ..api.api_v1 import api as api_v1  # noqa
  File "/app/app/api/api_v1/api.py", line 1, in <module>
    from .endpoints import role, token, user, utils, property, request  # noqa
  File "/app/app/api/api_v1/endpoints/token.py", line 54, in <module>
    'password': fields.Str(required=True)
  File "/usr/local/lib/python3.6/site-packages/flask_apispec/extension.py", line 121, in register
    resource_class_args, resource_class_kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_apispec/extension.py", line 68, in _defer
    bound()
  File "/usr/local/lib/python3.6/site-packages/flask_apispec/extension.py", line 136, in _register
    paths = self.view_converter.convert(target, endpoint, blueprint)
  File "/usr/local/lib/python3.6/site-packages/flask_apispec/apidoc.py", line 42, in convert
    return [self.get_path(rule, target, **kwargs) for rule in rules]
  File "/usr/local/lib/python3.6/site-packages/flask_apispec/apidoc.py", line 42, in <listcomp>
    return [self.get_path(rule, target, **kwargs) for rule in rules]
  File "/usr/local/lib/python3.6/site-packages/flask_apispec/apidoc.py", line 53, in get_path
    for method, view in six.iteritems(operations)
  File "/usr/local/lib/python3.6/site-packages/flask_apispec/apidoc.py", line 54, in <dictcomp>
    if method.lower() in (set(valid_methods) - {'head'})
  File "/usr/local/lib/python3.6/site-packages/flask_apispec/apidoc.py", line 66, in get_operation
    'parameters': self.get_parameters(rule, view, docs, parent),
  File "/usr/local/lib/python3.6/site-packages/flask_apispec/apidoc.py", line 97, in get_parameters
    extra_params += converter(schema, **options) if args else []
TypeError: fields2parameters() missing 1 required keyword-only argument: 'default_in'
```

[packages]
apispec = “==3.0.0”
celery = “==4.3.0"
redis = “==3.2.1”
couchbase = “*”
email-validator = “*”
emails = “==0.5.15"
fastapi = “==0.2.0”
flask = “==1.1.1"
flask-apispec = “==0.8.3”
flask-cors = “==3.0.8"
flask-jwt-extended = “==3.23.0”
ipython = “==7.4.0"
marshmallow = “==3.2.0”
passlib = {extras = [“bcrypt”],version = “==1.7.1”}
pydantic = “==0.18.2"
raven = {extras = [“flask”],version = “*”}
requests = “==2.21.0”
tenacity = “==5.0.3"
pandas = “==0.24.2”
xlrd = “>= 1.0.0"
python-dateutil = “==2.8.0”
firebase_admin = “==2.17.0"
sentry-sdk = “==0.11.2”
blinker = “==1.4"
flask-graphql = “==2.0.0”
graphene = “==2.1.7"

**Comment by jdramirezr** [comment]
Hi 
I also have the same error
`TypeError: fields2parameters() missing 1 required keyword-only argument: 'default_in'`

**Comment by sloria** [comment]
I don't have time to dig into this now. I would gladly review and merge a PR though.

**Comment by Aimage** [comment]
This can solve the problem but I didn't test all cases:
https://github.com/jmcarp/flask-apispec/pull/172

**Comment by oxhacks** [comment]
@sloria did you get see the contribution from @Aimage? This is blocking me from using this project as well. Thanks!

**Comment by AbdealiJK** [comment]
That fix doesn't look right because it would ignore other args that are set when `locations` is not set

**Comment by sloria** [comment]
Release 0.8.4 fixes this
