### ISSUE TITLE
DuplicateParameterException when using use_kwargs with OpenAPI 3

### ISSUE THREAD

**Issue by nat212** [jmcarp/flask-apispec#170]
Whenever I try and use OpenAPI 3 with flask-apispec, using use_kwargs gives the error:
`apispec.exceptions.DuplicateParameterError: Duplicate parameter with name body and location body`.
Here is a minimal `app.py` to reproduce:
```python
from flask import Flask
from apispec import APISpec
from apispec.ext.marshmallow import MarshmallowPlugin
from flask_apispec import FlaskApiSpec, MethodResource, use_kwargs
from marshmallow import Schema, fields

app = Flask(__name__)
app.config['APISPEC_SPEC'] = APISpec('test', 'v1.0', '3.0', plugins=[MarshmallowPlugin()])
docs = FlaskApiSpec(app)

class TestSchema(Schema):
    field1 = fields.Str()
    field2 = fields.Str()

class TestResource(MethodResource):
    @use_kwargs(TestSchema, locations=['json'])
    def get(self, field1, field2):
        return {'field1': field1, 'field2': field2}

app.add_url_rule('/', endpoint='testresource', view_func=TestResource.as_view('Test'))
docs.register(TestResource)


if __name__ == '__main__':
    app.run()
```

Installed pakages:
```
apispec==3.0.0
Click==7.0
Flask==1.1.1
flask-apispec==0.8.3
itsdangerous==1.1.0
Jinja2==2.10.3
MarkupSafe==1.1.1
marshmallow==3.2.1
six==1.12.0
webargs==5.5.2
Werkzeug==0.16.0```

Output of `python3 app.py`:
```
Traceback (most recent call last):
  File "app.py", line 21, in <module>
    docs.register(TestResource)
  File "/home/natasha/.virtualenvs/flat/lib/python3.6/site-packages/flask_apispec/extension.py", line 121, in register
    resource_class_args, resource_class_kwargs)
  File "/home/natasha/.virtualenvs/flat/lib/python3.6/site-packages/flask_apispec/extension.py", line 68, in _defer
    bound()
  File "/home/natasha/.virtualenvs/flat/lib/python3.6/site-packages/flask_apispec/extension.py", line 148, in _register
    self.spec.path(**path)
  File "/home/natasha/.virtualenvs/flat/lib/python3.6/site-packages/apispec/core.py", line 267, in path
    self.clean_operations(operations)
  File "/home/natasha/.virtualenvs/flat/lib/python3.6/site-packages/apispec/core.py", line 350, in clean_operations
    operation["parameters"] = self.clean_parameters(operation["parameters"])
  File "/home/natasha/.virtualenvs/flat/lib/python3.6/site-packages/apispec/core.py", line 318, in clean_parameters
    parameter["name"], parameter["in"]
apispec.exceptions.DuplicateParameterError: Duplicate parameter with name body and location body
```
Please help, as I would really like to use OpenAPI 3.

**Comment by nat212** [comment]
Changing the `openapi_version` parameter in the `APISpec` constructor to '2.0' runs perfectly fine.

**Comment by rosenloecher-it** [comment]
I run into another ApiSpec error (Non-integer code not allowed in OpenAPI < 3) because an auto generated options operation (by flask-apispec)
is not compatible!

My workaround:
```
app = Flask()

app.config.update({
    'APISPEC_SPEC': APISpec(
    	title="REST API",
        version="1.0.0",
        openapi_version="3.0.2",
        plugins=[
            DisableOptionsOperationPlugin(),
            # ...
        ],
    ),
    'APISPEC_SWAGGER_URL': '/swagger.json',
})

class DisableOptionsOperationPlugin(BasePlugin):

    def operation_helper(self, operations, **kwargs):
        # flask-apispec auto generates an options operation, which cannot handled by apispec.
        # apispec.exceptions.DuplicateParameterError: Duplicate parameter with name body and location body
        # => remove
        operations.pop("options", None)
```

**Comment by zrayn** [comment]
For the next person to dig into this issue, it appears to be coming from `apispec` and not be a `flask-apispec` issue. The offending line is https://github.com/marshmallow-code/apispec/blob/dev/src/apispec/ext/marshmallow/openapi.py#L232, here is the stack that gets you there:
```
  File ".../flask_apispec/extension.py", line 108, in register_existing_resources
    self.register(rule, blueprint=blueprint_name)
  File ".../flask_apispec/extension.py", line 125, in register
    self._defer(self._register, target, endpoint, blueprint,
  File ".../flask_apispec/extension.py", line 73, in _defer
    bound()
  File ".../flask_apispec/extension.py", line 141, in _register
    paths = self.view_converter.convert(target, endpoint, blueprint)
  File ".../flask_apispec/apidoc.py", line 43, in convert
    return [self.get_path(rule, target, **kwargs) for rule in rules]
  File ".../flask_apispec/apidoc.py", line 43, in <listcomp>
    return [self.get_path(rule, target, **kwargs) for rule in rules]
  File ".../flask_apispec/apidoc.py", line 55, in get_path
    'operations': {
  File ".../flask_apispec/apidoc.py", line 56, in <dictcomp>
    method.lower(): self.get_operation(rule, view, parent=parent)
  File ".../flask_apispec/apidoc.py", line 70, in get_operation
    'parameters': self.get_parameters(rule, view, docs, parent),
  File ".../flask_apispec/apidoc.py", line 103, in get_parameters
    extra_params += converter(schema, **options) if args else []
  File ".../apispec/ext/marshmallow/openapi.py", line 150, in schema2parameters
    return self.fields2parameters(fields, default_in=default_in)
  File ".../apispec/ext/marshmallow/openapi.py", line 171, in fields2parameters
    param = self.field2parameter(
  File ".../apispec/ext/marshmallow/openapi.py", line 201, in field2parameter
    return self.property2parameter(
  File ".../apispec/ext/marshmallow/openapi.py", line 232, in property2parameter
    ret["name"] = "body"
```

**Comment by arthuriantech** [comment]
So, I wrote a quick and dirty solution to this problem. https://gist.github.com/arthuriantech/f61fbb951eb2499effca87bfef4efa5f
