### ISSUE TITLE
TypeError when running unittest on app with Blueprints

### ISSUE THREAD

**Issue by nebularazer** [jmcarp/flask-apispec#56]
Given the following test app:

```python
# app.py
from flask import Blueprint, jsonify, Flask
from flask_apispec import FlaskApiSpec

docs = FlaskApiSpec()
blue = Blueprint('blue', __name__)


@blue.route('/', methods=['GET'])
def index():
    return jsonify({'test': 123})


def create_app():
    app = Flask(__name__)

    docs.init_app(app)

    app.register_blueprint(blue)
    docs.register_existing_resources()

    return app

app = create_app()

# test.py
import unittest

from flask import url_for

from app import create_app


class MyTestCase(unittest.TestCase):
    def setUp(self):
        self.app = create_app()
        self.app.config.update({'TESTING': True,
                                'SERVER_NAME': 'localhost'})
        self.app_context = self.app.app_context()
        self.app_context.push()
        self.client = self.app.test_client()

    def tearDown(self):
        self.app_context.pop()


class ApiTestCase(MyTestCase):

    def test_200(self):
        res = self.client.get(url_for('blue.index'))
        self.assertEqual(res.status_code, 200)


if __name__ == '__main__':
    unittest.main()
```

running the tests in test.py will raise:
```
Traceback (most recent call last):
  File "test.py", line 10, in setUp
    self.app = create_app()
  File "[..snip...]/app.py", line 16, in create_app
    docs.init_app(app)
  File "[..snip...]/venv/lib64/python3.6/site-packages/flask_apispec/extension.py", line 60, in init_app
    deferred()
  File "[..snip...]/venv/lib64/python3.6/site-packages/flask_apispec/extension.py", line 144, in _register
    raise TypeError()
TypeError
```

extending the TypeError to output the `target` gives:
`TypeError: (<bound method _PackageBoundObject.send_static_file of <Flask 'app'>>)`

**Comment by ArthurPBressan** [comment]
Also having this same issue.

**Comment by daenney** [comment]
Just ran into the exact same issue. Curiously I do not have this problem in development, only in testing. Which makes me wonder what is different when flask is run in testing mode that would trigger this.

**Comment by daenney** [comment]
Whenever the type error triggers it just seems mad about static files:
```
<bound method _PackageBoundObject.send_static_file of <Flask 'anonymau5'>>
<class 'method'>
send_static_file
```

**Comment by daenney** [comment]
So I patched the block of code to just `return None` once it gets a `types.MethodType` instead hoping that that would cause the error to disappear. It did, and here's the patch:

```python
elif isinstance(target, types.MethodType):
    return None
```

but then the next thing breaks:

```python
anonymau5/app.py:16: in create_app
    register_extensions(app)
anonymau5/app.py:28: in register_extensions
    apispec.init_app(app)
../../../../.virtualenv/anonymau5/lib/python3.6/site-packages/flask_apispec/extension.py:60: in init_app
    deferred()
../../../../.virtualenv/anonymau5/lib/python3.6/site-packages/flask_apispec/extension.py:135: in _register
    paths = self.view_converter.convert(target, endpoint, blueprint)
```

However, this turned out to be solvable on my side. In my `create_app` I was registering the extensions before I was registering the blueprints which seems to not matter when just doing a `flask run` (and seems to generally make more sense to me) but causes it to completely freak out under test. No clue why. In general I don't understand why this extension breaks all over once flask is started in testing mode.

**Comment by IamJeffG** [comment]
I am not sure this is related to testing mode, as @daenney says, but rather I find it happens upon calling `create_app()` a second time. I can reproduce the following regardless of whether `TESTING` is True or False.

It also happens even when the `create_app()` calls are split across different test files.

```python
import unittest

import mycustom.app


class TestFlaskApp(unittest.TestCase):

    def test_A(self):
        self.mycustom_app = mycustom.app.create_app()
        self.app = self.mycustom_app.test_client()
        self.assertFalse(False)

    def test_B(self):
        self.mycustom_app = mycustom.app.create_app()
        self.app = self.mycustom_app.test_client()
        self.assertTrue(True)
```

```
test_A (tests.test_flask_app_unit.TestFlaskApp) ... ok
test_B (tests.test_flask_app_unit.TestFlaskApp) ... ERROR

======================================================================
ERROR: test_B (tests.test_flask_app_unit.TestFlaskApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mycustom/tests/test_flask_app_unit.py", line 14, in test_B
    self.mycustom_app = mycustom.app.create_app()
  File "/mycustom/mycustom/app.py", line 62, in create_app
    docs.init_app(app)
  File "/usr/local/lib/python3.7/site-packages/flask_apispec/extension.py", line 60, in init_app
    deferred()
  File "/usr/local/lib/python3.7/site-packages/flask_apispec/extension.py", line 144, in _register
    raise TypeError()
TypeError

----------------------------------------------------------------------
Ran 2 tests in 0.006s

FAILED (errors=1)
```
