### ISSUE TITLE
marshal_with not working with return code

### ISSUE THREAD

**Issue by ashton** [jmcarp/flask-apispec#93]
works perfectly:

```python
@marshal_with(CreditCardResponseSchema)
def create_card():
    card = CreditCard()
    return card
```

returns an error:

```python
@marshal_with(CreditCardResponseSchema, code=201)
def create_card():
    card = CreditCard()
    return card
```

```
Traceback (most recent call last):
  File "/Users/john/.virtualenvs/real_state_app/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/john/.virtualenvs/real_state_app/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/john/.virtualenvs/real_state_app/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/john/.virtualenvs/real_state_app/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/john/.virtualenvs/real_state_app/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/john/.virtualenvs/real_state_app/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/john/.virtualenvs/real_state_app/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/john/.virtualenvs/real_state_app/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/john/.virtualenvs/real_state_app/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/john/.virtualenvs/real_state_app/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/john/.virtualenvs/real_state_app/lib/python3.6/site-packages/flask_jwt/__init__.py", line 177, in decorator
    return fn(*args, **kwargs)
  File "/Users/john/.virtualenvs/real_state_app/lib/python3.6/site-packages/flask_apispec/annotations.py", line 117, in wrapped
    return wrapper(*args, **kwargs)
  File "/Users/john/.virtualenvs/real_state_app/lib/python3.6/site-packages/flask_apispec/wrapper.py", line 34, in __call__
    return self.marshal_result(unpacked, status_code)
  File "/Users/john/.virtualenvs/real_state_app/lib/python3.6/site-packages/flask_apispec/wrapper.py", line 62, in marshal_result
    return format_output((format_response(output), ) + unpacked[1:])
  File "/Users/john/.virtualenvs/real_state_app/lib/python3.6/site-packages/flask/json.py", line 263, in jsonify
    (dumps(data, indent=indent, separators=separators), '\n'),
  File "/Users/john/.virtualenvs/real_state_app/lib/python3.6/site-packages/flask/json.py", line 123, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/Users/john/.virtualenvs/real_state_app/lib/python3.6/site-packages/flask/json.py", line 80, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'CreditCard' is not JSON serializable
```

**Comment by ashton** [comment]
if the object isn't JSON serializable, why it works when the return code is not specified? The object is serialized and returned correctly

**Comment by steinitzu** [comment]
I'm new to this framework, but I think this is what's happening:  
When you do `return card`, you are actually creating a response with the default status code (which is 200). There is no schema specified for code 200, so under the hood, you're basically getting the same result as: `return jsonify(card)`, instead of the desired result `return jsonify(CreditCardResponseSchema().dumps(card).data), 201`

So, I think just adding the 201 code to your return would fix it:

```python
@marshal_with(CreditCardResponseSchema, code=201)
def create_card():
    card = CreditCard()
    return card, 201
```

**Comment by euri10** [comment]
look at https://github.com/jmcarp/flask-apispec/issues/113
